nodeLinker: pnp
enableGlobalCache: false
pnpMode: strict
enableHardenedMode: true

packageExtensions:
  eslint-config-react-app@*:
    peerDependencies:
      "@babel/plugin-syntax-flow": "*"
      "@babel/plugin-transform-react-jsx": "*"
  eslint-plugin-flowtype@*:
    peerDependenciesMeta:
      "@babel/plugin-syntax-flow":
        optional: true
      "@babel/plugin-transform-react-jsx":
        optional: true

yarnPath: .yarn/releases/yarn-4.5.2.cjs
